examples/Laplacians_test.cpp, examples/Laplacians_test.sln, examples/sparsification_test.cpp, examples/sparsification_test.h, examples/tests.cpp, examples/tests.h, utils/graph/sparsify.cpp, utils/graph/sparsify.h, utils/solver/approxchol.cpp, utils/solver/approxchol.h, utils/solver/graphalgs.cpp, utils/solver/graphalgs.h, utils/solver/ijvstruct.cpp, utils/solver/ijvstruct.h, utils/solver/lapwrappers.cpp, utils/solver/lapwrappers.h, utils/solver/pcg_1.cpp, utils/solver/pcg_1.h, utils/solver/solvertypes.h, utils/solver/sparsecsc.cpp, utils/solver/sparsecsc.h
solvers and sparsification were added
=> solvers and sparsification were added

BUILD.md
Specify minimum required CMake version in the documentation
=> Specify minimum CMake version

examples/transform_examples/CMakeLists.txt, examples/transform_examples/assets/AudioFile.cpp, examples/transform_examples/assets/AudioFile.h, examples/transform_examples/wav_compressor.cpp, modules/distance/k-structured/TWED.cpp, modules/space/tree.cpp, modules/space/tree.hpp, modules/utils/pattern_compressor.cpp, modules/utils/pattern_compressor.hpp, tests/space_tests/space_tree_tests.cpp
Add pattern_compressor and pattern_compressor classes according to issue #48
=> Pattern compressor

modules/utils/graph/sparsify.cpp
Mostly cosmetic updates, but also one fix.
=> Kruskal sparsify init

modules/utils/crossfilter/include/detail/crossfilter.hpp, modules/utils/crossfilter/include/detail/crossfilter_impl.hpp, modules/utils/crossfilter/include/detail/impl/crossfilter_impl.ipp, modules/utils/crossfilter/test/crossfilter_test.cpp
Adding new methods to crossfilter
=> add dimenson_ptr and iterable_dimension_ptr to crossfilter

examples/distance_examples/earth_mover_distance_example.cpp, modules/distance/k-structured/EMD.cpp
fix for #73 Please, check if all is ok.
=> Updated EMD to use containers instead vector

modules/correlation/mgc.cpp, modules/correlation/mgc.hpp, tests/correlation_tests/correlation_tests.cpp
added the ability to use functional objects in the MGС class as metrics, issue #109
=> add support of general function objects to  MGC. issue #109

examples/distance_examples/CMakeLists.txt, modules/distance/k-random/CramervonNises.cpp, modules/distance/k-random/KolmogorovSmirnov.cpp, modules/distance/k-random/RandomEMD.cpp, modules/space/tree.hpp, modules/utils/graph.hpp, modules/utils/graph/graph.cpp, modules/utils/poor_mans_quantum/poor_mans_quantum.cpp, tests/distance_tests/CMakeLists.txt, tests/distance_tests/voi_tests.cpp, tests/mapping_tests/CMakeLists.txt, tests/mapping_tests/mapping_tests.cpp, tests/space_tests/CMakeLists.txt, tests/space_tests/space_matrix_tests.cpp, tests/space_tests/space_tree_tests.cpp
=> fix build on Linux

modules/utils/image_processing/image_filter.cpp, modules/utils/image_processing/image_filter.h
Usage example with CImg
```C++
#include <fstream>
#include <iostream>
#include "CImg/CImg.h"
#include "image_filter.h"
using namespace metric;
using namespace cimg_library;
using namespace std::chrono;
int main() {
CImg<unsigned char> input("img.png");
std::cout << "Read file" << std::endl;
auto rgbImg = iminit<uint8_t, 3>(input.height(), input.width(), 50);
for (int ch = 0; ch < rgbImg.size(); ++ch) {
for (int i = 0; i < rgbImg[ch].rows(); ++i) {
for (int j = 0; j < rgbImg[ch].columns(); ++j) {
rgbImg[ch](i, j) = input(j, i, 0, ch);
}
}
}
std::cout << "Created image " << rgbImg[0].rows() << "x" << rgbImg[0].columns() << " " << std::endl;
MotionFilter filter(10, 45);
PadModel<uint8_t> padmodel(PadDirection::BOTH, PadType::CONST);
auto start = system_clock::now();
Image<uint8_t, 3> …
```
=> Implement image filters based on Matlab's solution

examples/mapping_examples/CMakeLists.txt, examples/mapping_examples/KOC_MNIST_example.cpp, modules/utils/poor_mans_quantum.hpp, modules/utils/poor_mans_quantum/distributions/Binomial.cpp, modules/utils/poor_mans_quantum/distributions/Binomial.hpp, modules/utils/poor_mans_quantum/distributions/Discrete.cpp, modules/utils/poor_mans_quantum/distributions/Discrete.hpp, modules/utils/poor_mans_quantum/math_functions.cpp, modules/utils/poor_mans_quantum/poor_mans_quantum.cpp
=> Updated PMQ

examples/distance_examples/standart_distances_example.cpp, modules/distance/k-related/Standards.cpp, modules/distance/k-related/Standards.hpp
Euclidean metric on Blaze compressed objects
=> sparced Euclidean

examples/distance_examples/standart_distances_example.cpp, modules/distance/k-related/Standards.cpp, modules/distance/k-related/Standards.hpp, modules/utils.hpp
relax constraints for record types, required to support NumpyAdapters
=> suggest formatting, remove some static checks

examples/mapping_examples/CMakeLists.txt, python/pkg/metric/correlation/entropy.py, python/pkg/metric/correlation/mgc.py, python/pkg/metric/distance/__init__.py, python/pkg/metric/mapping/koc.py, python/pkg/metric/space/matrix.py, python/src/correlation/entropy.cpp, python/src/distance/init.cpp, python/src/distance/subs/CMakeLists.txt, python/src/distance/subs/standards.cpp, python/src/mapping/subs/affprop.cpp
some temporal fixes of python wrapper, just to make CI green
=> some temporal fixes of python wrapper, just to make CI green

modules/utils/image_processing/convolution.cpp
=> remove unused debug line produced warning

tests/space_tests/CMakeLists.txt, tests/space_tests/knn_graph_tests.cpp, tests/space_tests/space_matrix_tests.cpp, tests/space_tests/space_tree_tests.cpp
=> Tests space move to catch

tests/correlation_tests/CMakeLists.txt, tests/correlation_tests/correlation_tests.cpp
=> move correlation_tests to Catch2

tests/ensembles_tests/CMakeLists.txt, tests/ensembles_tests/ensemble_tests.cpp
=> move ensemble to catch2

tests/sparsification_tests/CMakeLists.txt, tests/sparsification_tests/sparsification_tests.cpp
=> move sparsification_tests to catch2

tests/space_tests/knn_graph_tests.cpp
=> comment negative parameters test

tests/utils/CMakeLists.txt, tests/utils/dsv_tests.cpp
=> move dsv_tests to catch2

tests/wrapper_tests/CMakeLists.txt, tests/wrapper_tests/lapack_tests.cpp
=> move lapack test to catch2

examples/correlation_examples/CMakeLists.txt, examples/energies_examples/CMakeLists.txt, examples/laplacians_example/CMakeLists.txt, examples/mapping_examples/CMakeLists.txt, examples/space_examples/CMakeLists.txt
=> remove unused boost from examples cmake scripts

examples/correlation_examples/CMakeLists.txt, examples/energies_examples/CMakeLists.txt, examples/ensemble_examples/CMakeLists.txt, examples/laplacians_example/CMakeLists.txt, examples/mapping_examples/CMakeLists.txt, examples/space_examples/CMakeLists.txt
=> Examples remove unused boost

.github/workflows/test.yml, .github/workflows/test_python.yml, examples/transform_examples/CMakeLists.txt, examples/transform_examples/wav_compressor.cpp
=> Examples remove boost po

CMakeLists.txt, modules/utils/dnn/Layer/Conv2d.h, modules/utils/image_processing/convolution.cpp, modules/utils/image_processing/image_filter.cpp, modules/utils/image_processing/image_filter.hpp, modules/utils/wrappers/lapack.hpp
=> Fix windows compilation

modules/utils/image_processing/convolution.cpp
=> remove pad model

modules/transform/wavelet.cpp
The generation of Daubechies matrices was too slow and took minutes for sizes more than 10000. Now it works milliseconds.
=> WIP: Optimize insertion to daubechies matrices

.github/workflows/benchmark.yml, .github/workflows/test-coverage.yml, .github/workflows/test-cpp-linux.yml, .github/workflows/test.yml
Put in order paths and names of workflows
=> Ci refactor paths and names

examples/transform_examples/dwt2_types_example.cpp, modules/transform/wavelet.cpp, modules/transform/wavelet.hpp, modules/transform/wavelet2d.hpp, tests/transform_test/wavelet_tests.cpp
* simplify code
* remove second parameter
=> Wavelet dbwavf refactor

.github/workflows/benchmark.yml, .github/workflows/test-coverage.yml, .github/workflows/test-cpp-linux.yml, CHANGELOG.md, CMakeLists.txt, README.md, cmake/panda_metric-config.cmake.in, examples/correlation_examples/intro_example.cpp, examples/tutorial.cpp, metric/metric.hpp, tests/distance_tests/kohonen_distance_tests.cpp, tests/space_tests/space_matrix_tests.cpp
* Add `find_dependency()` for metric cmake package
* Add cmake variables for tests, benchmarks and examples
* Move metric.hpp to metric/
* Add changelog
* Update and fix readme
* Update and fix CI
=> CMake install find_dependency(), add changelog, refactor, etc
